export const
    TODOS__COMPLETED_TODO_EXISTS = 'TODOS__COMPLETED_TODO_EXISTS',
    TODOS__COMPLETED_TODO_DOES_NOT_EXIST = 'TODOS__COMPLETED_TODO_DOES_NOT_EXIST',
    TODOS__NUMBER_OF_PENDING_TODOS = 'TODOS__NUMBER_OF_PENDING_TODOS',
    TODOS__HOW_MANY_TODOS = 'TODOS__HOW_MANY_TODOS',
    TODOS__UPDATE_STATUS_BAR_VISIBILITY = 'TODOS__UPDATE_STATUS_BAR_VISIBILITY',
    TODOS__ARE_YOU_A_COMPLETED_TODO = 'TODOS__ARE_YOU_A_COMPLETED_TODO',
    TODOS__ARE_YOU_A_PENDING_TODO = 'TODOS__ARE_YOU_A_PENDING_TODO';
